name: release-wf
on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The Version to be released'
        required: true
        default: '0.0.0'
        type: string
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build Packages (without tests)
        run: cd jamopp-ext.parent && ./mvnw -P build-deploy clean package -Dmaven.test.skip=true
      - name: Build Deploy Path
        shell: bash
        run: echo "DEPLOY_PATH=$( echo '${{ secrets.DEPLOYMENT_REMOTE_TARGET }}/extended-java-model-parser-and-printer' )" >> $GITHUB_ENV
      - name: Release Update Site
        uses: PalladioSimulator/Palladio-Build-ActionsPipeline-Deployment@master
        with:
          remote-user: ${{ secrets.DEPLOYMENT_REMOTE_USER }}
          remote-host: ${{ secrets.DEPLOYMENT_REMOTE_HOST }}
          remote-port: ${{ secrets.DEPLOYMENT_REMOTE_PORT }}
          server-ssh-key: ${{ secrets.DEPLOYMENT_SERVER_SSH_KEY }}
          local-source: './jamopp-ext.parent/jamopp-ext.p2/target/repository/*'
          remote-target: '${{ env.DEPLOY_PATH }}/release/${{ inputs.release-version }}'
          release-version: ${{ inputs.release-version }}
          link-path: ${{ env.DEPLOY_PATH }}
      - name: Setup Apache Maven Central
        uses: actions/setup-java@4.7.1
        with:
          java-version: 17
          distribution: 'temurin'
          server-id: central
          server-username: CENTRAL_USERNAME
          server-password: CENTRAL_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'
      - name: Deploy to Apache Maven Central
        run: cd jamopp-ext.parent && mvn -P deploy-mvn-central deploy
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: $${{ secrets.MAVEN_GPG_PASSPHRASE }}